name: Deploy to ECR
# updated ECR Repo assignment-1
on: 
  push:
    branches: [ main ]

jobs:

  build:

    name: Build Image
    runs-on: ubuntu-latest


    steps:

    - name: Check out code
      uses: actions/checkout@v4

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
        AWS_REGION: us-east-1

    - name: Build, test, tag, and push image to Amazon ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        WEBAPP_REPOSITORY: webapp-repo
        WEBAPP_TAG: webapp-v0.1
      run: |
        # Build the WebApp container
        docker build -t $ECR_REGISTRY/$WEBAPP_REPOSITORY:$WEBAPP_TAG -f Dockerfile .
        
        # Push WebApp container to ECR
        docker push $ECR_REGISTRY/$WEBAPP_REPOSITORY:$WEBAPP_TAG

    - name: Build, test, tag, and push MySQL image to Amazon ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        MYSQL_REPOSITORY: mysql-repo
        MYSQL_TAG: mysql-v0.1
      run: |
        # Build the MySQL container
        docker build -t $ECR_REGISTRY/$MYSQL_REPOSITORY:$MYSQL_TAG -f Dockerfile_mysql .
        
        # Push MySQL container to ECR
        docker push $ECR_REGISTRY/$MYSQL_REPOSITORY:$MYSQL_TAG
